//React imports
import React from 'react';
import { useQuery } from '@apollo/react-hooks';
import gql from 'graphql-tag';

//custom imports
import NavBar from '../components/Navbar';
//file generated by running npm run apollo:generate, this looks at our graphql schema and creates types for typescript based on the schema
import { getNonprofitData } from '../generated/getNonprofitData';
import pifLogo from '../media/icons/pif-logo.png';

//query to get nonprofit data currently set to only return the first nonprofit in the database
const GET_NONPROFIT_DATA = gql`
  query getNonprofitData {
    nonprofit(limit: 1) {
      display_name
      logo
      events {
        event_volunteers {
          id
        }
      }
    }
  }
`;

//this functional component renders the nonprofit dashboard
// Layout (from top --> bottom):
//Navbar, NonprofitInfo, Create Event Button, Edit Account Button, NonprofitDataGraph
const NonProfitDashboardPage = () => {
  const { loading, error, data } = useQuery<getNonprofitData>(
    GET_NONPROFIT_DATA,
  );

  if (loading || !data) return null;
  console.log(data);
  console.log(data.nonprofit[0]['display_name']);
  return (
    <div className="bg-blue-300 h-screen">
      {/* Navbar */}
      <NavBar />
      {/* Create Event Button need to add an onclick that routes to create event page */}
      <button
        type="button"
        className="shadow bg-blue-700 hover:bg-blue-600 focus:outline-none text-white font-bold py-1 px-4 rounded">
        Create Event
      </button>
      {/* Edit Account Button need to add an onclick that routes to edit account page? */}
      <button
        type="button"
        className="shadow bg-blue-700 hover:bg-blue-600 focus:outline-none text-white font-bold py-1 px-4 rounded">
        Edit Account
      </button>
      <div>
        {data.nonprofit[0]['display_name']}
        <img src={pifLogo} alt="event image" />
      </div>
    </div>
  );
};

export default NonProfitDashboardPage;
