// React Imports
import React, { useState } from 'react';
import { useQuery } from '@apollo/react-hooks';
import gql from 'graphql-tag';

// Custom Imports
import EventCard from './EventCard';
import notFoundGif from '../media/animations/event-not-found.gif';
import Modal from '../components/Modal';
//file generated by running npm run apollo:generate, this looks at our graphql schema and creates types for typescript based on the schema
import { getEvents } from '../generated/getEvents';
// This component holds multiple Event Cards accessible through scrolling
// Layout:
// List of Events

//graphql query object returns all events
const GET_EVENTS = gql`
  query getEvents {
    getEvents {
      id
      image
      title
      date
      location
      nonprofit {
        displayName
      }
    }
  }
`;

const EventCardCollection = () => {
  //useQuery hook takes our gql query and makes a request to the backend
  //the return value is held in data
  const [isModalOpen, setModalOpen] = useState(false);
  const [modalContent, setModalContent] = useState('');

  const toggleModal = () => {
    console.log('toggling modal');
    setModalOpen(!isModalOpen);
  };

  const { loading, error, data } = useQuery<getEvents>(GET_EVENTS);
  if (loading || !data) return null;
  return (
    <div>
      <Modal isModalOpen={isModalOpen} modalContent={modalContent} />
      {!error ? (
        <div>
          <div>
            {/* List Of Events from Props */}
            {data.getEvents.map(event => {
              return (
                <EventCard
                  event={event}
                  key={event.id}
                  setModalContent={setModalContent}
                  toggleModal={toggleModal}
                />
              );
            })}
          </div>
        </div>
      ) : (
        <div className="event-list-page-image-container flex justify-center items-center">
          <div className="event-list-page-image-container flex flex-col justify-center items-center">
            <img className="h-64" src={notFoundGif} alt="" />
            <h2 className="block font-bold text-lg">
              Oops! Couldn't Find Any Events!
            </h2>
          </div>
        </div>
      )}
    </div>
  );
};

export default EventCardCollection;
