// React imports
import React from 'react';

//file generated by running npm run apollo:generate, this looks at our graphql schema and creates types for typescript based on the schema
import { getNonprofits_getNonprofits } from '../generated/getNonprofits';

interface Props {
  nonprofit: getNonprofits_getNonprofits;
}

// Component Layout: Nonprofit Logo, Nonprofit information
const NonprofitCard = ({ nonprofit }: Props) => {
  const { displayName, logo, mission } = nonprofit;
  return (
    <div className="flex flex-row justify-end pb-2">
      {/* Nonprofit Logo */}
      <div className="flex justify-center items-center bg-white h-24 w-24">
        <img src={logo} alt="" />
      </div>
      {/* Nonprofit Information */}
      <div className="flex flex-col pl-2 bg-blue-400 w-64 h-24">
        <h1 className="text-s font-bold">{displayName}</h1>
        <h1 className="text-xs">{mission}</h1>
      </div>
    </div>
  );
};

export default NonprofitCard;
