// React imports
import React from 'react';
import './CardComponent.scss';

//file generated by running npm run apollo:generate, this looks at our graphql schema and creates types for typescript based on the schema
import { getNonprofits_getNonprofits } from '../generated/getNonprofits';

interface Props {
  nonprofit: getNonprofits_getNonprofits;
}

// Component Layout: Nonprofit Logo, Nonprofit information
const NonprofitCard = ({ nonprofit }: Props) => {
  const { displayName, logo, mission } = nonprofit;
  return (
    <div className="flexBoxContainer">
      {/* Nonprofit Logo */}
      <div className="imageFlexBox">
        <img src={logo} alt="nonprofit logo" />
      </div>
      {/* Nonprofit Information */}
      <div className="cardInfo">
        <h1 className="title">{displayName}</h1>
        <h1>{mission}</h1>
      </div>
    </div>
  );
};

export default NonprofitCard;
